#!/bin/bash
#SBATCH --account=<your-account>
#SBATCH --partition=<your-partition>
#SBATCH --mail-user=<your-email-address>
#SBATCH --mail-type=END,FAIL
#SBATCH --time=24:00:00
#SBATCH --mem=8G
#SBATCH --cpus-per-task=4
#SBATCH --output=<where-the-logs-go>/pilot.out
#SBATCH --error=<where-the-logs-go>/pilot.err

python run-bic-mobo.py -r slurm
